services:
    ####################
    # Public Services ##
    ####################
    storage_manager:
        class: Opensoft\StorageBundle\Storage\StorageManager
        public: true
        arguments:
            - '@doctrine'
            - '@opensoft_storage.gaufrette_adapter_resolver'
            - '@opensoft_storage.url_resolver'
            - '@opensoft_storage.key_generator'
            - '@opensoft_storage.storage_type_provider'
    opensoft_storage.gaufrette_adapter_resolver:
        class: Opensoft\StorageBundle\Storage\GaufretteAdapterResolver
        public: true

    # Form Types
    storage.form_type.storage_adapter_options_type:
        class: Opensoft\StorageBundle\Form\Type\StorageAdapterOptionsType
        public: true
        arguments:
            - '@opensoft_storage.gaufrette_adapter_resolver'
        tags:
            - { name: 'form.type' }
    storage.form_type.stored_files_filter_type:
        class: Opensoft\StorageBundle\Form\Type\StoredFilesFilterType
        public: true
        arguments:
            - '@opensoft_storage.storage_type_provider'
        tags:
            - { name: 'form.type' }

    # Early request listener for permanent URL redirection support
    opensoft_storage.early_request_listener:
        class: Opensoft\StorageBundle\EventListener\RequestListener
        public: true
        arguments:
            - '@doctrine'
            - '@opensoft_storage.storage_type_provider'
            - '@opensoft_storage.request_matcher.default_request_matcher'
        tags:
            - { name: 'kernel.event_subscriber', lazy: true }

    opensoft_storage.form.extension.help_type:
        class: Opensoft\StorageBundle\Form\Extension\HelpTypeExtension
        tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    #####################
    # Private Services ##
    #####################
    opensoft_storage.checks.local_storage:
        class: Opensoft\StorageBundle\Check\LocalStorageCheck
        public: false
        arguments:
            - '@doctrine'
            - '@storage_manager'
            - '@opensoft_storage.gaufrette_adapter_resolver'
        tags:
            - { name: 'liip_monitor.check', alias: 'local_storage' }

    opensoft_storage.url_resolver:
        class: Opensoft\StorageBundle\Storage\StorageUrlResolver
        public: false
        arguments:
            - '@opensoft_storage.gaufrette_adapter_resolver'

    opensoft_storage.key_generator:
        class: Opensoft\StorageBundle\Storage\StorageKeyGenerator
        public: false

    opensoft_storage.twig_extension:
        class: Opensoft\StorageBundle\Twig\Extension\TwigExtension
        public: false
        arguments:
            - '@opensoft_storage.url_resolver'
        tags:
            - { name: 'twig.extension' }

    opensoft_storage.doctrine_event_subscriber:
        class: Opensoft\StorageBundle\EventListener\StorageListener
        public: false
        arguments:
            - '@storage_manager'
            - '@logger'
        tags:
            - { name: 'doctrine.event_subscriber', lazy: true }
            - { name: 'monolog.logger', channel: 'storage'}

    # Permanent URL Request Matchers (currently only the http_host matcher exists)
    opensoft_storage.request_matcher.http_host_request_matcher:
        class: Opensoft\StorageBundle\Storage\RequestMatcher\HttpHostRequestMatcher
        public: false
        arguments:
            - '%opensoft_storage.parameter.permanent.http_host%'

    # Adapters (make sure they're tagged with 'opensoft_storage.adapter')
    opensoft_storage.adapter.aws_s3:
        class: Opensoft\StorageBundle\Storage\Adapter\AwsS3AdapterConfiguration
        public: false
        arguments:
            - '@router'
            - '%opensoft_storage.parameter.permanent_base_url%'
        tags:
            - { name: 'opensoft_storage.adapter' }
    opensoft_storage.adapter.local:
        class: Opensoft\StorageBundle\Storage\Adapter\LocalAdapterConfiguration
        public: false
        arguments:
            - '@router'
            - '@assets.packages'
            - '%opensoft_storage.parameter.permanent_base_url%'
        tags:
            - { name: 'opensoft_storage.adapter' }
